FESTIVAL_MAPPINGS = {
    ("Chaitra", "Shukla Pratipada"): "Gudi Padwa",
    ("Chaitra", "Shukla Navami"): "Rama Navami",
    ("Chaitra", "Shukla Purnima"): "Hanuman Jayanti",
    ("Vaishakha", "Shukla Tritiya"): "Akshay Tritiya",
    ("Vaishakha", "Shukla Panchami"): "Vasant Panchami",
    ("Vaishakha", "Shukla Purnima"): "Buddha Pornima",
    ("Jyeshtha", "Shukla Purnima"): "Holi Purnima",
    ("Ashadha", "Shukla Ekadashi"): "Ashadhi Devshayani Ekadashi",
    ("Shravana", "Shukla Panchami"): "Nagpanchami",
    ("Shravana", "Shukla Purnima"): "Rakshabandhan",
    ("Shravana", "Krushna Ashtami"): "Shreekrishna Janmashtami",
    ("Shravana", "Krushna Amavasya"): "Bailpola",
    ("Bhadrapada", "Shukla Chaturthi"): "Ganesha Chaturthi",
    ("Bhadrapada", "Shukla Shashthi"): "Gauri Avahan",
    ("Bhadrapada", "Shukla Saptami"): "Gauri Poojan",
    ("Bhadrapada", "Shukla Ashtami"): "Gauri Visarjan",
    ("Ashwina", "Shukla Pratipada"): "Navaratri",
    ("Ashwina", "Shukla Dashami"): "Dussehra",
    ("Ashwina", "Krushna Ashtami"): "Dhan Trayodashi",
    ("Ashwina", "Krushna Chaturdashi"): "Narak Chaturdashi",
    ("Ashwina", "Krushna Amavasya"): "Diwali (Lakshmi Puja)",
    ("Kartika", "Shukla Ekadashi"): "Kartiki Ekadashi",
    ("Kartika", "Shukla Pratipada"): "Diwali Padawa",
    ("Kartika", "Shukla Dwitiya"): "Bhai Dooj",
    ("Kartika", "Shukla Purnima"): "Dev Diwali",
    ("Magha", "Shukla Chaturthi"): "Ganesh Jayanti",
    ("Magha", "Shukla Saptami"): "Rathsaptami",
    ("Magha", "Krushna Trayodashi"): "Mahashivaratri",
    ("Phalguna", "Shukla Purnima"): "Holi",
    ("Phalguna", "Krushna Pratipada"): "Dhulivandan",
    ("Margashirsha", "Shukla Purnima"): "Datta Jayanti",
}
